version: '3.9'

services:
  postgres:
    image: postgres:18.3-alpine3.23
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ecommerce_fullstack
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
